name: Scrape Talk Locations (PR)

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ master ]        # <-- change to main if that's your default
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

concurrency:
  group: scrape-talks-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install --upgrade getorg

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Create/update PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated update of talk locations"
          branch: automation/talks
          title: "Automated update of talk locations"
          body: "This PR updates talk locations generated by the workflow."
          base: master             # <-- change to main if needed
          delete-branch: true
