name: Build and Deploy Site

on:
  push:
    branches:
      - main  # Ensure you're working on the correct branch
  workflow_dispatch:

permissions:
  contents: write     # Allow the bot to commit and push changes to the repo
  pages: write        # Allow the bot to deploy to GitHub Pages
  id-token: write     # Allow the bot to request ID tokens for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll site
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
