name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write     # Allow the bot to commit and push changes back to the repo
  pages: write        # Allow the bot to deploy to GitHub Pages
  id-token: write     # Allow the bot to use OIDC for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site with Jekyll
      run: |
        bundle exec jekyll build  # This will generate the _site/ directory

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
