name: Scrape Talk Locations

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ master ]           # <-- change to [ main ] if that's your default
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # full history so rebase works
          ref: master              # <-- change to main if needed

      # (A) Ensure we're in sync with the latest remote BEFORE generating changes
      - name: Sync with remote
        run: |
          git fetch origin master
          git checkout master
          # Fast-forward to remote; fail if not possible (prevents diverged history)
          git merge --ff-only origin/master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install --upgrade getorg

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # (B) Commit, rebase on top of the newest remote, then push
      - name: Commit and push automated updates
        run: |
          git add -A
          git commit -m "Automated update of talk locations" || echo "No changes"
          # Rebase our commit(s) on top of remote to avoid non-fast-forward errors
          git pull --rebase origin master || true
          git push origin HEAD:master
