name: Scrape Talk Locations

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ master ]           # <-- change to main if needed
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master              # <-- change to main

      # Always start from the latest remote state
      - name: Sync to latest remote
        run: |
          git fetch origin master
          git reset --hard origin/master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install --upgrade getorg

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push automated updates
        run: |
          git add -A
          git commit -m "Automated update of talk locations" || echo "No changes"
          # Safe-force in case someone pushed during this run
          git push --force-with-lease origin HEAD:master
