name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'

permissions:
  contents: write       # Allows commit and push access
  pull-requests: write  # Allows creating and approving pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Create pull request with updates
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Automated update of talk locations
        branch: automation/talks
        title: Automated update of talk locations
        body: This PR updates talk locations generated by the workflow.
        base: master
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN to authenticate
